### ISSUE TITLE
contribution not possible 

### ISSUE THREAD

**Issue by MarBeije** [MauritsDK/Textmining#1]
he,

ik kan niet schrijven in jou textmining repository.
''Uploads are disabled. - File uploads require push access to this repository.''
zou je dat kunnen geven? Dit kan bij _settings-> manage access_ 

thanks,
Marin

**Comment by MauritsDK** [comment]
Je zit er nu in



Sent from my Samsung Galaxy smartphone.



-------- Original message --------
